### ISSUE TITLE
might as well uglify js too

### ISSUE THREAD

**Issue by stevenvachon** [Rebelmail/posthtml-uglify#3]
or rename this package to `posthtml-uglifycss` if it's specifically for css

**Comment by voischev** [comment]
look at https://github.com/maltsev/htmlnano

**Comment by stevenvachon** [comment]
Cool.

I had honestly misinterpreted what this package does. It should seriously be renamed to something more descriptive such as `posthtml-mangle-ids`.

**Comment by devinus** [comment]
Only because of your familiarity with UglifyJS, otherwise what the hell does `uglify` mean anyways?

Just porting over our old plugin which had some users already so they'll find this new PostHTML version easy enough. Otherwise, we might rename it in the future.

**Comment by stevenvachon** [comment]
If you want people to know what your plugin is, then communication is key.
